// components/home/data.js

export const POPULAR_LOCATIONS = ["Bangkok", "Nonthaburi", "Pathumthani"];

export const LOCATIONS = [
  {
    id: 1,
    name: "Co-Working Space Bangkok",
    address: "Bangkok, Thailand",
    hours: "Open 24 hours",
    wifi: true,
    rating: 4.7,
    reviews: 543,
    price: 50,
    image: "https://mpics.mgronline.com/pics/Images/561000009686901.JPEG",
  },
  {
    id: 2,
    name: "Co-Working Space Bangkok",
    address: "Bangkok, Thailand",
    hours: "Open 24 hours",
    wifi: true,
    rating: 4.5,
    reviews: 543,
    price: 50,
    image: "https://mpics.mgronline.com/pics/Images/561000009686901.JPEG",
  },
  {
    id: 3,
    name: "Co-Working Space Bangkok",
    address: "Bangkok, Thailand",
    hours: "Open 24 hours",
    wifi: true,
    rating: 4.5,
    reviews: 543,
    price: 50,
    image: "https://mpics.mgronline.com/pics/Images/561000009686901.JPEG",
  },
  {
    id: 4,
    name: "Co-Working Space Bangkok",
    address: "Bangkok, Thailand",
    hours: "Open 24 hours",
    wifi: true,
    rating: 3.5,
    reviews: 543,
    price: 50,
    image: "https://mpics.mgronline.com/pics/Images/561000009686901.JPEG",
  },
  {
    id: 5,
    name: "Co-Working Space Bangkok",
    address: "Bangkok, Thailand",
    hours: "Open 24 hours",
    wifi: true,
    rating: 3.5,
    reviews: 543,
    price: 50,
    image: "https://mpics.mgronline.com/pics/Images/561000009686901.JPEG",
  },
  {
    id: 6,
    name: "Co-Working Space Bangkok",
    address: "Bangkok, Thailand",
    hours: "Open 24 hours",
    wifi: true,
    rating: 3.5,
    reviews: 543,
    price: 50,
    image: "https://mpics.mgronline.com/pics/Images/561000009686901.JPEG",
  },
  {
    id: 7,
    name: "Co-Working Space Bangkok",
    address: "Bangkok, Thailand",
    hours: "Open 24 hours",
    wifi: true,
    rating: 3.5,
    reviews: 543,
    price: 50,
    image: "https://mpics.mgronline.com/pics/Images/561000009686901.JPEG",
  },

];
